name: Receive Backup from College-ERP

on:
  workflow_dispatch:

jobs:
  pull-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B (without GITHUB_TOKEN)
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Clone College-ERP Repo
        run: |
          git clone https://ReaveND:${{ secrets.COLLEGE_ERP_PAT }}@github.com/ReaveND/College-ERP.git college-erp

      - name: Create backup folder and copy files
        run: |
          mkdir -p backups/$(date +%F)
          rsync -av --delete --exclude='.git' college-erp/ backups/$(date +%F)/

      - name: Remove temporary clone
        run: |
          rm -rf college-erp

      - name: Purge leftover submodule metadata
        run: |
          if [ -f .gitmodules ]; then
            git rm --cached .gitmodules
            rm .gitmodules
          fi
          git rm --cached college-erp || true

      - name: Commit, Tag & Push to Repo B via PAT
        env:
          TOKEN: ${{ secrets.COLLEGE_ERP_PAT }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          # Commit any new backup files
          git add .
          git commit -m "Backup from College-ERP on $(date)" || echo "No changes to commit"

          # Build a date-based tag
          TAG="backup-$(date +%F)"

          # Check if the tag already exists on remote
          if git ls-remote --exit-code --tags "https://ReaveND:${TOKEN}@github.com/ReaveND/College-ERP-Backup.git" "refs/tags/$TAG"; then
            echo "Tag $TAG already exists on remote, skipping tag creation."
          else
            git tag "$TAG"
            git push "https://ReaveND:${TOKEN}@github.com/ReaveND/College-ERP-Backup.git" "$TAG"
          fi

          # Finally push the commit to main
          git push "https://ReaveND:${TOKEN}@github.com/ReaveND/College-ERP-Backup.git" HEAD:main
